### PR TITLE
Support Hash as an argument to the goToStep function

### PR DESCRIPTION
**Pull request by GabrielFerrarini**

### CODE REVIEW

**Comment by GabrielFerrarini** [comment]
@jcmcneal For your review

**Comment by jcmcneal** [comment]
Looks great, thank you!

**Comment by jcmcneal** [comment]
@GabrielFerrarini can you just update the README to reflect your changes?

**Comment by GabrielFerrarini** [comment]
@jcmcneal My vscode `format on save` changed some formatting in the README as well. Let me know if this is ok or if I should revert to the previous content only put my actual changes (which are [here](https://github.com/jcmcneal/react-step-wizard/pull/83/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R89) and [here](https://github.com/jcmcneal/react-step-wizard/pull/83/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R143))

**Comment by jcmcneal** [comment]
Those changes are okay

**Pull request merged**
